# Run the tests on a native Ubuntu machine
name: Test on regular Ubuntu

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  az_name: wsl-ci-2
  az_resource_group: wsl

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        shell: bash
        run:
          set -eu
          DEBIAN_FRONTEND=noninteractive apt update
          DEBIAN_FRONTEND=noninteractive apt install -y python3
      - name: Run tests
        shell: bash
        run: python3 test.py github-runner
